### ISSUE TITLE
Auto run pre-push test testing required.

### ISSUE THREAD

**Issue by Randy1Burrell** [supertokens/supertokens-node-mysql-ref-jwt#10]
# What's the problem?
While developing, committing and pushing to remote git there is no way for tests to automatically run locally before actually pushing my code to remote.

# Why is this a problem?
It would be useful because there would be an easy way to give me feedback on the repository's tests before I pushed my code and break something.

# Any suggestions?
Used an auto pre-push dev lib to run tests on git hook pre-push.

**Comment by rishabhpoddar** [comment]
You can now run tests via ```npm test```
Please see our [Contributing](https://github.com/supertokens/supertokens-node-mysql-ref-jwt/blob/master/CONTRIBUTING.md) guide
