### ISSUE TITLE
[Feature] Add ssl option to mysql config

### ISSUE THREAD

**Issue by enlightenedmouse** [supertokens/supertokens-node-mysql-ref-jwt#23]
Please add the ability to have an ssl connection property proxied to the underlying mysql connection.

**Comment by bhumilsarvaiya** [comment]
Hi @enlightenedmouse. I have pushed the required changes to the latest release [v4.4.0](https://github.com/supertokens/supertokens-node-mysql-ref-jwt/commit/a9cc8a883a4ab973de3329f47ecf171e4de8dc11). You can now pass ssl connection property in the mysql config options :v:

**Comment by rishabhpoddar** [comment]
Please confirm that this issue has been solved, so we can close it.

**Comment by enlightenedmouse** [comment]
Works great @bhumilsarvaiya : ) Thanks.
