### ISSUE TITLE
Please explain the technology used in this project.

### ISSUE THREAD

**Issue by vaibssingh** [supertokens/supertokens-node-mysql-ref-jwt#7]
In the docs, add an explanation of how session management and its handling is done for any newcomers.

**Comment by rishabhpoddar** [comment]
For now, please have a look at [this blog post](https://medium.com/@supertokens.io/91f27eeef460) to get an understanding of the higher level protocol being used.
We will soon add notes to the WiKi section explaining the technical aspects in much more detail!
