### ISSUE TITLE
The lib has not been properly tested.

### ISSUE THREAD

**Issue by Randy1Burrell** [supertokens/supertokens-node-mysql-ref-jwt#9]
# What the problem?
I see no written regression or proof tests within the lib.

# Why is this a problem?
Code that are untested cannot be trusted because they provide no proof that it actually does what it says it will do or any regression tests for prohibitive measures of regression.

# Any suggestion to fix this?
Please write some tests as mentioned in the README.md.

**Comment by rishabhpoddar** [comment]
We have added many tests for this library, and are continuously adding more. Instructions on how to run tests can be found in our [Contributing](https://github.com/supertokens/supertokens-node-mysql-ref-jwt/blob/master/CONTRIBUTING.md) guide
